<?php
/**
 * BatchesApi
 * PHP version 5
 *
 * @category Class
 * @package  PaymentRails\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Rails API
 *
 * No descripton provided (generated by PaymentRails Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.30.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PaymentRails\Client\Api;

use \PaymentRails\Client\Configuration;
use \PaymentRails\Client\ApiClient;
use \PaymentRails\Client\ApiException;
use \PaymentRails\Client\ObjectSerializer;

/**
 * BatchesApi Class Doc Comment
 *
 * @category Class
 * @package  PaymentRails\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BatchesApi
{

    /**
     * API Client
     *
     * @var \PaymentRails\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \PaymentRails\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\PaymentRails\Client\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.railz.io/v1');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \PaymentRails\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \PaymentRails\Client\ApiClient $apiClient set the API client
     *
     * @return BatchesApi
     */
    public function setApiClient(\PaymentRails\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation createBatch
     *
     * 
     *
     * @param \PaymentRails\Client\Model\BatchPost $body B-XXXXXXXXXXXXXXXX (required)
     * @return \PaymentRails\Client\Model\Batch
     * @throws \PaymentRails\Client\ApiException on non-2xx response
     */
    public function createBatch($body)
    {
        list($response) = $this->createBatchWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation createBatchWithHttpInfo
     *
     * 
     *
     * @param \PaymentRails\Client\Model\BatchPost $body B-XXXXXXXXXXXXXXXX (required)
     * @return Array of \PaymentRails\Client\Model\Batch, HTTP status code, HTTP response headers (array of strings)
     * @throws \PaymentRails\Client\ApiException on non-2xx response
     */
    public function createBatchWithHttpInfo($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling createBatch');
        }
        // parse inputs
        $resourcePath = "/batches";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-api-key');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-api-key'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\PaymentRails\Client\Model\Batch',
                '/batches'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\PaymentRails\Client\Model\Batch', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\PaymentRails\Client\Model\Batch', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation queryBatches
     *
     * 
     *
     * @param string $start_date  (optional)
     * @param string $end_date  (optional)
     * @param string $status filter one or more status. multiple value comma separated (optional)
     * @return \PaymentRails\Client\Model\InlineResponse200
     * @throws \PaymentRails\Client\ApiException on non-2xx response
     */
    public function queryBatches($start_date = null, $end_date = null, $status = null)
    {
        list($response) = $this->queryBatchesWithHttpInfo($start_date, $end_date, $status);
        return $response;
    }

    /**
     * Operation queryBatchesWithHttpInfo
     *
     * 
     *
     * @param string $start_date  (optional)
     * @param string $end_date  (optional)
     * @param string $status filter one or more status. multiple value comma separated (optional)
     * @return Array of \PaymentRails\Client\Model\InlineResponse200, HTTP status code, HTTP response headers (array of strings)
     * @throws \PaymentRails\Client\ApiException on non-2xx response
     */
    public function queryBatchesWithHttpInfo($start_date = null, $end_date = null, $status = null)
    {
        // parse inputs
        $resourcePath = "/batches";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // query params
        if ($start_date !== null) {
            $queryParams['startDate'] = $this->apiClient->getSerializer()->toQueryValue($start_date);
        }
        // query params
        if ($end_date !== null) {
            $queryParams['endDate'] = $this->apiClient->getSerializer()->toQueryValue($end_date);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = $this->apiClient->getSerializer()->toQueryValue($status);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-api-key');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-api-key'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\PaymentRails\Client\Model\InlineResponse200',
                '/batches'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\PaymentRails\Client\Model\InlineResponse200', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\PaymentRails\Client\Model\InlineResponse200', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

}
