codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true
  allow_coverage_offsets: true
  ci:
    - circleci.com

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
