<?php
/**
 * BatchPaymentPost
 *
 * PHP version 5
 *
 * @category Class
 * @package  PaymentRails\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Rails API
 *
 * No descripton provided (generated by PaymentRails Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.30.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PaymentRails\Client\Model;

use \ArrayAccess;

/**
 * BatchPaymentPost Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     PaymentRails\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchPaymentPost implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'BatchPaymentPost';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'recipient' => '\PaymentRails\Client\Model\BatchPaymentRecipient',
        'source_amount' => 'float',
        'source_currency' => 'string',
        'source_currency_name' => 'string',
        'target_amount' => 'float',
        'target_currency' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'recipient' => 'recipient',
        'source_amount' => 'sourceAmount',
        'source_currency' => 'sourceCurrency',
        'source_currency_name' => 'sourceCurrencyName',
        'target_amount' => 'targetAmount',
        'target_currency' => 'targetCurrency'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'recipient' => 'setRecipient',
        'source_amount' => 'setSourceAmount',
        'source_currency' => 'setSourceCurrency',
        'source_currency_name' => 'setSourceCurrencyName',
        'target_amount' => 'setTargetAmount',
        'target_currency' => 'setTargetCurrency'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'recipient' => 'getRecipient',
        'source_amount' => 'getSourceAmount',
        'source_currency' => 'getSourceCurrency',
        'source_currency_name' => 'getSourceCurrencyName',
        'target_amount' => 'getTargetAmount',
        'target_currency' => 'getTargetCurrency'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['recipient'] = isset($data['recipient']) ? $data['recipient'] : null;
        $this->container['source_amount'] = isset($data['source_amount']) ? $data['source_amount'] : null;
        $this->container['source_currency'] = isset($data['source_currency']) ? $data['source_currency'] : null;
        $this->container['source_currency_name'] = isset($data['source_currency_name']) ? $data['source_currency_name'] : null;
        $this->container['target_amount'] = isset($data['target_amount']) ? $data['target_amount'] : null;
        $this->container['target_currency'] = isset($data['target_currency']) ? $data['target_currency'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets recipient
     * @return \PaymentRails\Client\Model\BatchPaymentRecipient
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     * @param \PaymentRails\Client\Model\BatchPaymentRecipient $recipient
     * @return $this
     */
    public function setRecipient($recipient)
    {
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets source_amount
     * @return float
     */
    public function getSourceAmount()
    {
        return $this->container['source_amount'];
    }

    /**
     * Sets source_amount
     * @param float $source_amount
     * @return $this
     */
    public function setSourceAmount($source_amount)
    {
        $this->container['source_amount'] = $source_amount;

        return $this;
    }

    /**
     * Gets source_currency
     * @return string
     */
    public function getSourceCurrency()
    {
        return $this->container['source_currency'];
    }

    /**
     * Sets source_currency
     * @param string $source_currency source currency code
     * @return $this
     */
    public function setSourceCurrency($source_currency)
    {
        $this->container['source_currency'] = $source_currency;

        return $this;
    }

    /**
     * Gets source_currency_name
     * @return string
     */
    public function getSourceCurrencyName()
    {
        return $this->container['source_currency_name'];
    }

    /**
     * Sets source_currency_name
     * @param string $source_currency_name currency name
     * @return $this
     */
    public function setSourceCurrencyName($source_currency_name)
    {
        $this->container['source_currency_name'] = $source_currency_name;

        return $this;
    }

    /**
     * Gets target_amount
     * @return float
     */
    public function getTargetAmount()
    {
        return $this->container['target_amount'];
    }

    /**
     * Sets target_amount
     * @param float $target_amount
     * @return $this
     */
    public function setTargetAmount($target_amount)
    {
        $this->container['target_amount'] = $target_amount;

        return $this;
    }

    /**
     * Gets target_currency
     * @return string
     */
    public function getTargetCurrency()
    {
        return $this->container['target_currency'];
    }

    /**
     * Sets target_currency
     * @param string $target_currency target currency code
     * @return $this
     */
    public function setTargetCurrency($target_currency)
    {
        $this->container['target_currency'] = $target_currency;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\PaymentRails\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\PaymentRails\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


