<?php
/**
 * BatchPaymentPostTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PaymentRails\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Rails API
 *
 * No descripton provided (generated by PaymentRails Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.31.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PaymentRails\Client;

/**
 * BatchPaymentPostTest Class Doc Comment
 *
 * @category    Class */
// * @description BatchPaymentPost
/**
 * @package     PaymentRails\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchPaymentPostTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BatchPaymentPost"
     */
    public function testBatchPaymentPost()
    {

    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {

    }

    /**
     * Test attribute "source_amount"
     */
    public function testPropertySourceAmount()
    {

    }

    /**
     * Test attribute "source_currency"
     */
    public function testPropertySourceCurrency()
    {

    }

    /**
     * Test attribute "source_currency_name"
     */
    public function testPropertySourceCurrencyName()
    {

    }

    /**
     * Test attribute "target_amount"
     */
    public function testPropertyTargetAmount()
    {

    }

    /**
     * Test attribute "target_currency"
     */
    public function testPropertyTargetCurrency()
    {

    }

}
