<?php
/**
 * RecipientApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PaymentRails\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Rails API
 *
 * No descripton provided (generated by PaymentRails Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.31.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PaymentRails\Client;

use \PaymentRails\Client\Configuration;
use \PaymentRails\Client\ApiClient;
use \PaymentRails\Client\ApiException;
use \PaymentRails\Client\ObjectSerializer;

/**
 * RecipientApiTest Class Doc Comment
 *
 * @category Class
 * @package  PaymentRails\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RecipientApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createBankAccount
     *
     * .
     *
     */
    public function testCreateBankAccount()
    {

    }

    /**
     * Test case for createPaypalAccount
     *
     * .
     *
     */
    public function testCreatePaypalAccount()
    {

    }

    /**
     * Test case for createRecipientPayoutMethods
     *
     * .
     *
     */
    public function testCreateRecipientPayoutMethods()
    {

    }

    /**
     * Test case for deleteRecipient
     *
     * .
     *
     */
    public function testDeleteRecipient()
    {

    }

    /**
     * Test case for getBankAccount
     *
     * .
     *
     */
    public function testGetBankAccount()
    {

    }

    /**
     * Test case for getPaypalAccount
     *
     * .
     *
     */
    public function testGetPaypalAccount()
    {

    }

    /**
     * Test case for getRecipient
     *
     * .
     *
     */
    public function testGetRecipient()
    {

    }

    /**
     * Test case for getRecipientInfo
     *
     * .
     *
     */
    public function testGetRecipientInfo()
    {

    }

    /**
     * Test case for getRecipientPayoutMethods
     *
     * .
     *
     */
    public function testGetRecipientPayoutMethods()
    {

    }

    /**
     * Test case for queryRecipientComplianceHistory
     *
     * .
     *
     */
    public function testQueryRecipientComplianceHistory()
    {

    }

    /**
     * Test case for queryRecipientLogHistory
     *
     * .
     *
     */
    public function testQueryRecipientLogHistory()
    {

    }

    /**
     * Test case for queryRecipientPaymentHistory
     *
     * .
     *
     */
    public function testQueryRecipientPaymentHistory()
    {

    }

    /**
     * Test case for updateBankAccount
     *
     * .
     *
     */
    public function testUpdateBankAccount()
    {

    }

    /**
     * Test case for updatePaypalAccount
     *
     * .
     *
     */
    public function testUpdatePaypalAccount()
    {

    }

    /**
     * Test case for updateRecipient
     *
     * .
     *
     */
    public function testUpdateRecipient()
    {

    }

    /**
     * Test case for updateRecipientInfo
     *
     * .
     *
     */
    public function testUpdateRecipientInfo()
    {

    }

    /**
     * Test case for updateRecipientPayoutMethods
     *
     * .
     *
     */
    public function testUpdateRecipientPayoutMethods()
    {

    }

}
